### ISSUE TITLE
traceback with http proxy code

### ISSUE THREAD

**Issue by mikemccracken** [ubuntu/conjure-up#134]
```
(conjure-dev) mmccrack@blackbox:~/conjure-up⟫ conjure-up -d battlemidget/openstack-novalxd
Traceback (most recent call last):
  File "/home/mmccrack/conjure-up/conjure-dev/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up', 'console_scripts', 'conjure-up')()
  File "/home/mmccrack/conjure-up/conjure/app.py", line 154, in main
    apply_proxy()
  File "/home/mmccrack/conjure-up/conjure/app.py", line 125, in apply_proxy
    if app.arg.http_proxy:
AttributeError: 'types.SimpleNamespace' object has no attribute 'arg'
```

**Comment by battlemidget** [comment]
https://github.com/ubuntu/conjure-up/commit/09af2474f6353954049fead574374e0bd1937961
