### ISSUE TITLE
Invalid markup element ServerError(ServerError(…), ‘unknown version (1) of interface “Application”’)

### ISSUE THREAD

**Issue by jleavers** [ubuntu/conjure-up#163]
maas 2.0.0 (beta7+bzr5112)
juju 2.0-beta8-xenial-amd64
conjure-up 2.0.0

conjure-up openstack displays the error when choosing the first application (ceph).

```
$ conjure-up openstack
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1326, in run
    self._loop.run_forever()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 331, in run_forever
    self._run_once()
  File "/usr/lib/python3.5/asyncio/base_events.py", line 1298, in _run_once
    handle._run()
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/ubuntui/views/error.py", line 41, in cancel
    raise SystemExit("Install exited because of error.")
SystemExit: Install exited because of error.
Install exited because of error.
```

**Comment by jleavers** [comment]
I have rebuilt the 3x nodes used to test and tried again - this time I was able to step through all 17 application steps, but at the end it failed again:

```
$ conjure-up openstack
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/service_walkthrough.py", line 194, in do_deploy
    self.callback(single_service=self.service)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 47, in finish
    return render()
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 80, in render
    return finish(single_service=None)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 58, in finish
    return controllers.use('deploystatus').render()
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 53, in render
    this.view = DeployStatusView(app)
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 17, in __init__
    self.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 23, in refresh_nodes
    for name, service in sorted(status['Applications'].items()):
KeyError: KeyError('Applications',)
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 214, in main
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/service_walkthrough.py", line 194, in do_deploy
    self.callback(single_service=self.service)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 47, in finish
    return render()
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 80, in render
    return finish(single_service=None)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 58, in finish
    return controllers.use('deploystatus').render()
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 53, in render
    this.view = DeployStatusView(app)
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 17, in __init__
    self.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 23, in refresh_nodes
    for name, service in sorted(status['Applications'].items()):
KeyError: KeyError('Applications',)
```

**Comment by battlemidget** [comment]
Yea between juju beta 8 and juju beta 9 they changed all the references of services to 'applications'.

They just released the beta 9 of juju I would suggest updating to that beta and giving it a try again.

**Comment by battlemidget** [comment]
Also we're doing another release this Monday June 20th that will have further support for maas 2.0 and juju beta 9. Unless you're comfortable building from git I recommend waiting until then to try again.
