### ISSUE TITLE
Doesn't work ootb for OpenStack

### ISSUE THREAD

**Issue by SaMnCo** [ubuntu/conjure-up#167]
I am on the unstable channel from the ppa, on Xenial and for the last 2 weeks I am getting the below error. Can't understand what it is I need to fix.

```
$ conjure-up openstack
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 500, in process_input
    event, button, col, row, focus=True ):
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 649, in mouse_event
    return self._current_widget.mouse_event(size, event, button, x, y, focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1169, in mouse_event
    event, button, col, row-htrim, focus )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 666, in mouse_event
    focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 903, in mouse_event
    event, button, col, row-top, focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1687, in mouse_event
    focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 666, in mouse_event
    focus)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 557, in mouse_event
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/service_walkthrough.py", line 197, in do_skip_rest
    self.callback(single_service=None)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 58, in finish
    return controllers.use('deploystatus').render()
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 53, in render
    this.view = DeployStatusView(app)
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 17, in __init__
    self.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 23, in refresh_nodes
    for name, service in sorted(status['Applications'].items()):
KeyError: KeyError('Applications',)
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 214, in main
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 500, in process_input
    event, button, col, row, focus=True ):
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 649, in mouse_event
    return self._current_widget.mouse_event(size, event, button, x, y, focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1169, in mouse_event
    event, button, col, row-htrim, focus )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 666, in mouse_event
    focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 903, in mouse_event
    event, button, col, row-top, focus)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1687, in mouse_event
    focus)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 666, in mouse_event
    focus)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 557, in mouse_event
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/service_walkthrough.py", line 197, in do_skip_rest
    self.callback(single_service=None)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 58, in finish
    return controllers.use('deploystatus').render()
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 53, in render
    this.view = DeployStatusView(app)
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 17, in __init__
    self.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 23, in refresh_nodes
    for name, service in sorted(status['Applications'].items()):
KeyError: KeyError('Applications',)
```

**Comment by battlemidget** [comment]
You need at least Juju beta 9 has they changed some things internally wrt Services -> Applications. I'm doing a release today that checks for at least beta 9 and gives you a better error message if that requirement isn't met.

**Comment by battlemidget** [comment]
Fixed in latest ppa
