### ISSUE TITLE
Doesn't work with Juju 2.0 and MAAS 2.0

### ISSUE THREAD

**Issue by battlemidget** [ubuntu/conjure-up#199]
pulled from https://github.com/Ubuntu-Solutions-Engineering/conjure-up.io/issues/1

I pointed this tool at my MAAS region controller, supplied my API key, and chose all defaults. One node (out of nine) got provisioned but there was a long period of no visible activity except some message like CONJURE UP OPENSTACK in orange. Finally I got the below stacktrace. I'm using

```
conjure-up      2.0.0.3-0~459~ubuntu16.04.1
juju            2.0-beta10-0ubuntu1~16.04.1~juju1
maas            2.0.0~beta8+bzr5134-0ubuntu1~xenial1

```
$ conjure-up openstack

```
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 46, in __refresh
    this.view.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 22, in refresh_nodes
    status = model_status()
  File "/usr/share/conjure-up/conjure/juju.py", line 36, in _decorator
    return f(*args, **kwargs)
  File "/usr/share/conjure-up/conjure/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/usr/share/conjure-up/macumba/v2.py", line 113, in _request
    'Params': params})
  File "/usr/share/conjure-up/macumba/v2.py", line 124, in call
    return self.receive(req_id, timeout)
  File "/usr/share/conjure-up/macumba/api.py", line 119, in receive
    res = self.conn.do_receive(request_id)
  File "/usr/share/conjure-up/macumba/ws.py", line 75, in do_receive
    raise ConnectionClosedError
macumba.errors.ConnectionClosedError
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 270, in main
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 46, in __refresh
    this.view.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 22, in refresh_nodes
    status = model_status()
  File "/usr/share/conjure-up/conjure/juju.py", line 36, in _decorator
    return f(*args, **kwargs)
  File "/usr/share/conjure-up/conjure/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/usr/share/conjure-up/macumba/v2.py", line 113, in _request
    'Params': params})
  File "/usr/share/conjure-up/macumba/v2.py", line 124, in call
    return self.receive(req_id, timeout)
  File "/usr/share/conjure-up/macumba/api.py", line 119, in receive
    res = self.conn.do_receive(request_id)
  File "/usr/share/conjure-up/macumba/ws.py", line 75, in do_receive
    raise ConnectionClosedError
macumba.errors.ConnectionClosedError
```

**Comment by battlemidget** [comment]
Should be resolved in 2.0.0.4 and onwards
