### ISSUE TITLE
Not accepting MAAS credentials in input field

### ISSUE THREAD

**Issue by mafischer** [ubuntu/conjure-up#220]
![conjure-up](https://cloud.githubusercontent.com/assets/1082176/16640568/a7ba88c6-43be-11e6-9198-7c785888fe70.png)

```
Jul  3 20:23:33 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 20:23:34 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 20:24:07 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 20:24:07 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 20:25:09 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 20:25:09 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 20:31:52 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 20:31:52 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 20:35:26 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.shan.maas-oauth: expected string, got nothing
Jul  3 20:35:26 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 20:36:03 fischerapps conjure-up/openstack: [DEBUG] app.py:86 - Beta release found, checking minimum requirements.
Jul  3 20:36:17 fischerapps conjure-up/openstack: [DEBUG] gui.py:53 - Performing bootstrap: davina maas/localhost
Jul  3 20:36:17 fischerapps conjure-up/openstack: [DEBUG] juju.py:136 - bootstrap cmd: juju bootstrap davina maas/localhost --upload-tools --config image-stream=daily --config enable-os-refresh-update=false --config enable-os-upgrade=false --bootstrap-series=xenial --credential margorie
Jul  3 20:36:17 fischerapps conjure-up/openstack: [DEBUG] gui.py:54 - Rendering GUI controller for Variant
Jul  3 20:36:19 fischerapps conjure-up/openstack: [DEBUG] gui.py:29 - handle bootstrap
Jul  3 20:36:19 fischerapps conjure-up/openstack: [ERROR] gui.py:36 - ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 20:36:19 fischerapps conjure-up/openstack: [ERROR] __init__.py:19 - Showing dialog for exception:#012NoneType
Jul  3 20:44:04 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.shan.maas-oauth: expected string, got nothing
Jul  3 20:44:04 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 21:01:59 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.shan.maas-oauth: expected string, got nothing
Jul  3 21:01:59 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 21:03:38 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 21:03:38 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 21:05:43 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 21:05:43 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 21:07:00 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.shan.maas-oauth: expected string, got nothing
Jul  3 21:07:01 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 21:07:27 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 21:07:27 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  3 21:07:28 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 37, in __pre_deploy_exec#012    juju.get_current_model())['provider-type']#012  File "/usr/share/conjure-up/conjure/juju.py", line 34, in _decorator#012    login()#012  File "/usr/share/conjure-up/conjure/juju.py", line 79, in login#012    raise Exception("Tried to login to a non bootstrapped environment.")#012Exception: Tried to login to a non bootstrapped environment.
Jul  3 21:38:51 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  3 21:38:51 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  6 21:01:07 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  6 21:01:07 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
Jul  6 21:04:51 fischerapps conjure-up/openstack: [ERROR] ERROR loading credentials: credentials.maas.kaliyah.maas-oauth: expected string, got nothing
Jul  6 21:04:51 fischerapps conjure-up/openstack: [ERROR] Showing dialog for exception:#012NoneType
```

**Comment by mafischer** [comment]
clearing out the ~/.local/share/juju/credentials.yaml file resolved this issue. seems to be related to https://bugs.launchpad.net/juju-core/+bug/1581748
