### ISSUE TITLE
Failure in deploy-done (#012glannce/0: hook failed: "install")

### ISSUE THREAD

**Issue by hyyperlite** [ubuntu/conjure-up#233]
As executed with both ppa:conjure/next and ppa:conjure/daily and ppa:juju/devel since I could not even get nearly this far when attempting with stable.   Ubuntu 16.04

```
**combined.log:**
Jul 12 09:52:25 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:52:30 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:52:33 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:52:38 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:52:41 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:52:46 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:52:48 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:52:53 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:52:56 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:01 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:04 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:09 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:12 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:17 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:20 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:25 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:27 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:32 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:35 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:40 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:43 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:48 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:51 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:53:56 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:53:59 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:20 - Running pre-deploy for OpenStack
Jul 12 09:54:04 lxd1 conjure-up/openstack: [DEBUG] 00_pre-deploy:32 - Processing lxd profile: default
Jul 12 09:54:09 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:54:21 lxd1 conjure-up/openstack: message repeated 2 times: [ [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.]
Jul 12 09:54:27 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:54:34 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:54:47 lxd1 conjure-up/openstack: message repeated 2 times: [ [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.]
Jul 12 09:54:53 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:54:59 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:55:17 lxd1 conjure-up/openstack: message repeated 3 times: [ [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.]
Jul 12 09:55:24 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:55:30 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:55:56 lxd1 conjure-up/openstack: message repeated 4 times: [ [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.]
Jul 12 09:56:04 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:56:10 lxd1 conjure-up/openstack: [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.
Jul 12 09:56:23 lxd1 conjure-up/openstack: message repeated 2 times: [ [DEBUG] 00_deploy-done:13 - Running deploy-done for OpenStack installation.]
Jul 12 09:56:24 lxd1 conjure-up/openstack: [ERROR] Failure in deploy done: Deployment errors:#012glance/0: hook failed: "install"
Jul 12 09:56:24 lxd1 conjure-up/openstack: [ERROR] Showing dialog for exception:#012Traceback (most recent call last):#012  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run#012    result = self.fn(*self.args, **self.kwargs)#012  File "/usr/share/conjure-up/conjure/controllers/deploystatus/common.py", line 38, in wait_for_applications#012    raise Exception(result['message'])#012Exception: Deployment errors:#012glance/0: hook failed: "install"

**stdout**:
[info] Loading current openstack spells from Juju Charmstore, please wait.
[info] Installing additional required packages: openstack
[info] Loading current openstack spells from Juju Charmstore, please wait.
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 47, in __refresh
    this.view.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 21, in refresh_nodes
    status = model_status()
  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator
    return f(*args, **kwargs)
  File "/usr/share/conjure-up/conjure/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request
    'Params': params})
  File "/usr/share/conjure-up/macumba/v2.py", line 129, in call
    return self.receive(req_id, timeout)
  File "/usr/share/conjure-up/macumba/api.py", line 119, in receive
    res = self.conn.do_receive(request_id)
  File "/usr/share/conjure-up/macumba/ws.py", line 75, in do_receive
    raise ConnectionClosedError
macumba.errors.ConnectionClosedError
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 305, in main
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 47, in __refresh
    this.view.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 21, in refresh_nodes
    status = model_status()
  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator
    return f(*args, **kwargs)
  File "/usr/share/conjure-up/conjure/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request
    'Params': params})
  File "/usr/share/conjure-up/macumba/v2.py", line 129, in call
    return self.receive(req_id, timeout)
  File "/usr/share/conjure-up/macumba/api.py", line 119, in receive
    res = self.conn.do_receive(request_id)
  File "/usr/share/conjure-up/macumba/ws.py", line 75, in do_receive
    raise ConnectionClosedError
macumba.errors.ConnectionClosedError
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
    pr.write(f)
  File "/usr/lib/python3/dist-packages/problem_report.py", line 402, in write
    file.write(v.replace(b'\n', b'\n '))
OSError: [Errno 28] No space left on device

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 146, in apport_excepthook
    pr.write(f)
OSError: [Errno 28] No space left on device

Original exception was:
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 305, in main
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 164, in cb
    callback(self, user_data)
  File "/usr/share/conjure-up/conjure/controllers/deploystatus/gui.py", line 47, in __refresh
    this.view.refresh_nodes()
  File "/usr/share/conjure-up/conjure/ui/views/deploystatus.py", line 21, in refresh_nodes
    status = model_status()
  File "/usr/share/conjure-up/conjure/juju.py", line 35, in _decorator
    return f(*args, **kwargs)
  File "/usr/share/conjure-up/conjure/api/models.py", line 42, in model_status
    return juju.CLIENT.Client(request="FullStatus")
  File "/usr/share/conjure-up/macumba/v2.py", line 118, in _request
    'Params': params})
  File "/usr/share/conjure-up/macumba/v2.py", line 129, in call
    return self.receive(req_id, timeout)
  File "/usr/share/conjure-up/macumba/api.py", line 119, in receive
    res = self.conn.do_receive(request_id)
  File "/usr/share/conjure-up/macumba/ws.py", line 75, in do_receive
    raise ConnectionClosedError
macumba.errors.ConnectionClosedError
```

**Comment by battlemidget** [comment]
```
OSError: [Errno 28] No space left on device
```

Are you out of disk space?

**Comment by battlemidget** [comment]
Thanks for the update, your gui crashing issue has recently cropped up and I have a bug for it here: https://github.com/ubuntu/conjure-up/issues/231

We'll work through that issue there and close this one out.
