### ISSUE TITLE
traceback in service walkthrough for apache mapreduce bundle

### ISSUE THREAD

**Issue by battlemidget** [ubuntu/conjure-up#260]
```
Exception in ev.run():
Traceback (most recent call last):
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/conjure_up-2.0.0-py3.5.egg/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/home/adam/.pyenv/versions/3.5.1/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/conjure_up-2.0.0-py3.5.egg/conjure/ui/views/service_walkthrough.py", line 183, in _update_readme_on_main_thread
    firstparidx = nrls.index('')
ValueError: '' is not in list
Traceback (most recent call last):
  File "/home/adam/.pyenv/versions/conjure-dev35/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/conjure_up-2.0.0-py3.5.egg/conjure/app.py", line 305, in main
    EventLoop.run()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/conjure_up-2.0.0-py3.5.egg/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/home/adam/.pyenv/versions/3.5.1/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/home/adam/.pyenv/versions/conjure-dev35/lib/python3.5/site-packages/conjure_up-2.0.0-py3.5.egg/conjure/ui/views/service_walkthrough.py", line 183, in _update_readme_on_main_thread
    firstparidx = nrls.index('')
ValueError: '' is not in list
```

The bundle I'm testing against is:
https://github.com/battlemidget/bundle-apache-processing-mapreduce/tree/patch-conjurfied

**Comment by battlemidget** [comment]
@mikemccracken FYI, going to try and track down whats happening as well
