### ISSUE TITLE
Stack Trace on conjure-up bigdata

### ISSUE THREAD

**Issue by arosales** [ubuntu/conjure-up#40]
I did the following:

`apt install conjure-up` #per instructions
`conjure-up bigdata
`
In the menu
- choose Apache Flume/Spark/Zeppelin
- choose local host

get:

```
arosales@x230:~$ conjure-up bigdata
Exception in ev.run():
Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/share/conjure-up/conjure/ui/views/cloud.py", line 21, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/cloud.py", line 72, in submit
    self.cb(result.label, create_cloud=True)
  File "/usr/share/conjure-up/conjure/controllers/cloud.py", line 39, in finish
    return self.app.controllers['newcloud'].render(cloud)
  File "/usr/share/conjure-up/conjure/controllers/newcloud.py", line 118, in render
    creds,
UnboundLocalError: local variable 'creds' referenced before assignment
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==0.1.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 222, in main
    app.start()
  File "/usr/share/conjure-up/conjure/app.py", line 171, in start
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/share/conjure-up/conjure/ui/views/cloud.py", line 21, in keypress
    return super().keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/cloud.py", line 72, in submit
    self.cb(result.label, create_cloud=True)
  File "/usr/share/conjure-up/conjure/controllers/cloud.py", line 39, in finish
    return self.app.controllers['newcloud'].render(cloud)
  File "/usr/share/conjure-up/conjure/controllers/newcloud.py", line 118, in render
    creds,
UnboundLocalError: local variable 'creds' referenced before assignment
arosales@x230:~$ conjure-up --version
conjure-up 0.1.0
arosales@x230:~$ uname -a
Linux x230 4.4.0-22-generic #40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
arosales@x230:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04 LTS"
arosales@x230:~$ 
```

**Comment by battlemidget** [comment]
Thanks, Do you have anything in your ~/.local/share/juju/credentials.yaml already? (this is for reproducing so you can clear out any passwords)

**Comment by arosales** [comment]
Nothing in "~/.local/share/juju/credentials.yaml" file, no controllers bootstrapped atm.

**Comment by battlemidget** [comment]
Thanks I'll try and reproduce today

**Comment by arosales** [comment]
Note, this stack occurs for me no matter which bundle I choose.

**Comment by battlemidget** [comment]
@arosales are you running conjure-up 0.1.0? If so, can you try the one from xenial-updates 0.1.1?

**Comment by battlemidget** [comment]
@arosales nm it shows up on 0.1.1

**Comment by battlemidget** [comment]
bug for tracking SRU https://bugs.launchpad.net/ubuntu/+source/conjure-up/+bug/1586131

**Comment by unixfox** [comment]
I've the same bug from a fresh install for Openstack and Ubuntu.
How to install conjure-up 0.1.1 (I'm running on the 0.1.0 version) ?

**Comment by battlemidget** [comment]
Im working on something that I'll push to a ppa so you guys can test

**Comment by battlemidget** [comment]
Can you guys try 0.1.2 from the ppa?  https://launchpad.net/~conjure/+archive/ubuntu/ppa

**Comment by battlemidget** [comment]
Ive gotten confirmation that at least 1 person had a successful run with the latest fixes. I've uploaded to both xenial and yakkety and it should be making it's way into the proposed queue. If you don't want to wait for that process feel free to use the PPA described previously.
