### ISSUE TITLE
PPA Install resulting in no spell found

### ISSUE THREAD

**Issue by stephen-kainos** [ubuntu/conjure-up#54]
Adding the /next ppa for conjure-up on 16.04 and installing the conjure-up results in [warning] Could not find spell in charmstore when running `conjure-up openstack`

**Comment by battlemidget** [comment]
@stephen-kainos thanks for testing, for now can you edit /etc/conjure-up.conf and change 'blessed: True' to 'blessed: False'

Right now I've got 2 spells in the registry for testing that isn't ready for primetime just yet

**Comment by battlemidget** [comment]
We've also got several fixes in today that haven't been packaged yet in the PPA, ill kick off a build of it in the next hour though

**Comment by stephen-kainos** [comment]
thanks, I've been able to start the install process now. Once I tell it to deploy the services it gives me the following stacktrace

`Traceback (most recent call last):
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/service_walkthrough.py", line 80, in do_skip_rest
    self.callback(service=None)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 40, in finish
    return controllers.use('finish').render()
  File "/usr/share/conjure-up/conjure/controllers/finish/gui.py", line 177, in render
    info = model_info(app.current_model)
  File "/usr/share/conjure-up/conjure/juju.py", line 27, in _decorator
    login()
  File "/usr/share/conjure-up/conjure/juju.py", line 72, in login
    raise Exception("Tried to login to a non bootstrapped environment.")
Exception: Tried to login to a non bootstrapped environment.
Traceback (most recent call last):
  File "/usr/bin/conjure-up", line 9, in <module>
    load_entry_point('conjure-up==2.0.0', 'console_scripts', 'conjure-up')()
  File "/usr/share/conjure-up/conjure/app.py", line 204, in main
    EventLoop.run()
  File "/usr/share/conjure-up/ubuntui/ev.py", line 83, in run
    cls.loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 278, in run
    self._run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 376, in _run
    self.event_loop.run()
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 1328, in run
    raise self._exc_info[0](self._exc_info[1]).with_traceback(self._exc_info[2])
  File "/usr/lib/python3.5/asyncio/events.py", line 125, in _run
    self._callback(*self._args)
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 393, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3/dist-packages/urwid/raw_display.py", line 493, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 403, in _update
    self.process_input(keys)
  File "/usr/lib/python3/dist-packages/urwid/main_loop.py", line 503, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 643, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1128, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 836, in keypress
    return self._original_widget.keypress((maxcol,), key)
  File "/usr/lib/python3/dist-packages/urwid/container.py", line 1587, in keypress
    key = self.focus.keypress(tsize, key)
  File "/usr/lib/python3/dist-packages/urwid/decoration.py", line 621, in keypress
    return self._original_widget.keypress(maxvals, key)
  File "/usr/lib/python3/dist-packages/urwid/wimp.py", line 535, in keypress
    self._emit('click')
  File "/usr/lib/python3/dist-packages/urwid/widget.py", line 463, in _emit
    signals.emit_signal(self, name, self, *args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 264, in emit
    result |= self._call_callback(callback, user_arg, user_args, args)
  File "/usr/lib/python3/dist-packages/urwid/signals.py", line 294, in _call_callback
    return bool(callback(*args_to_pass))
  File "/usr/share/conjure-up/conjure/ui/views/service_walkthrough.py", line 80, in do_skip_rest
    self.callback(service=None)
  File "/usr/share/conjure-up/conjure/controllers/deploy/gui.py", line 40, in finish
    return controllers.use('finish').render()
  File "/usr/share/conjure-up/conjure/controllers/finish/gui.py", line 177, in render
    info = model_info(app.current_model)
  File "/usr/share/conjure-up/conjure/juju.py", line 27, in _decorator
    login()
  File "/usr/share/conjure-up/conjure/juju.py", line 72, in login
    raise Exception("Tried to login to a non bootstrapped environment.")
Exception: Tried to login to a non bootstrapped environment.`

**Comment by battlemidget** [comment]
This was fixed in the latest 2.0.0.1 pushed out yesterday.
