### ISSUE TITLE
hang after pressing 'q' from deploy status screen

### ISSUE THREAD

**Issue by mikemccracken** [ubuntu/conjure-up#73]
after waiting for a while in the deploy status screen after filing #72, I pressed 'q' to exit, and the urwid UI cleared back to the prompt, but the program hasn't exited.

if I ^C, I get this traceback:

```python-traceback

^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 39, in _python_exit
    t.join()
  File "/usr/lib/python3.5/threading.py", line 1054, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.5/threading.py", line 1070, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt

```

**Comment by battlemidget** [comment]
We need to be able to force kill a juju deploy/bootstrap if someone hits 'q' otherwise this future waits until those operations are done
